interface ExampleMessage {
    attribute double x;
	attribute double y;
	attribute double z;
	attribute double yaw;
	attribute double roll;
	attribute double pitch;
	attribute list float random_points;
	attribute list float z_random_points;
}